### ISSUE TITLE
Hall of fame ?

### ISSUE THREAD

**Issue by Lucas-C** [jacksonbenete/email_terminal#6]
Hi!

Thank you for making & sharing this, it is awesome!

A friend of mine did something similar a year ago, based on [terminaljs](https://github.com/eosterberg/terminaljs), for a game of [Mothership](https://www.mothershiprpg.com): it was really great, but he did not open-source it so far.

I noticed there are 61 forks of your repo: do you think it could be interesting to add a simple "hall of fame" section in the README, to list all the terminals made by people using this framework. I'd love to know what people have created with it!

Regards

**Comment by jacksonbenete** [comment]
Hello Lucas,

I'm amazed that up to date we keep receiving forks on it, considering that I only shared about this project once in a very small subreddit back in April 2020, and never shared or talked about it again...

I'm glad you liked!

A hall of fame is a very nice idea, though I wonder how it would be curated, and if there's no curation I guess that the forks page is already the list of people using it.

If you have any ideas on how this hall of fame could work, we can talk about it further and if you want to create it you can open a pull request and I'll accept it though I'm not sure how we could rate or select the forks.

This was a very simple project that works completely on the frontend, so it could be "hosted" on github pages so people don't have to pay for servers or domain names.
Unfortunately as we're only processing on the frontend we can't give commands to the server and we can't work on files, everything must be done on json files and we can just emulate some simple commands.
I guess that having to edit json files might put some people off from trying to play with it, since json can be very tiring to write.

I'm working on a new version slightly more complex, but using a backend programming language so it could be hosted and work on files and emulate more complex commands. But it's still very experimental and I'm not with too much free time lately, but soon I hope I can put it together and open source it.

**Comment by Lucas-C** [comment]
I opened https://github.com/jacksonbenete/email_terminal/pull/8 in order to start something

**Comment by jacksonbenete** [comment]
Nice, very clean contributions, it's already merged.

Do you think we should notify the mentioned users about it?
Even though their forks are "open source", they contain creative content.
I don't know how it works. ahaha Sometimes people can get mad even though it's something so simple.

**Comment by Lucas-C** [comment]
I don't think that's needed no, but they may appreciate to be pinged about it :)
Maybe a simple way to do so could be to open an issue in their fork to notify them about this mention?

I'm closing this issue now, but I may open a new one with ideas for new features...
